package data;
// Generated 20/09/2017 9:54:48 PM by Hibernate Tools 5.2.3.Final

/**
 * Emp2 generated by hbm2java
 */
public class Emp2 implements java.io.Serializable {

	private Integer id;
	private String fname;
	private String lname;
	private String department;
	private String city;
	private String hobby;

	public Emp2() {
	}

	public Emp2(String fname, String lname, String department, String city, String hobby) {
		this.fname = fname;
		this.lname = lname;
		this.department = department;
		this.city = city;
		this.hobby = hobby;
	}
	
	public Emp2(int id, String fname, String lname, String department, String city, String hobby) {
		this.id = id;
		this.fname = fname;
		this.lname = lname;
		this.department = department;
		this.city = city;
		this.hobby = hobby;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((city == null) ? 0 : city.hashCode());
		result = prime * result + ((department == null) ? 0 : department.hashCode());
		result = prime * result + ((fname == null) ? 0 : fname.hashCode());
		result = prime * result + ((hobby == null) ? 0 : hobby.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((lname == null) ? 0 : lname.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) return true;
		if (obj == null) return false;
		if (getClass() != obj.getClass()) return false;
		Emp2 other = (Emp2) obj;
		if (city == null) {
			if (other.city != null) return false;
		} else if (!city.equals(other.city)) return false;
		if (department == null) {
			if (other.department != null) return false;
		} else if (!department.equals(other.department)) return false;
		if (fname == null) {
			if (other.fname != null) return false;
		} else if (!fname.equals(other.fname)) return false;
		if (hobby == null) {
			if (other.hobby != null) return false;
		} else if (!hobby.equals(other.hobby)) return false;
		if (id == null) {
			if (other.id != null) return false;
		} else if (!id.equals(other.id)) return false;
		if (lname == null) {
			if (other.lname != null) return false;
		} else if (!lname.equals(other.lname)) return false;
		return true;
	}

	@Override
	public String toString() {
		return "Emp2 [id=" + id + ", fname=" + fname + ", lname=" + lname + ", department=" + department + ", city="
				+ city + ", hobby=" + hobby + "]";
	}

}
